### ISSUE TITLE
Slack API no longer works?

### ISSUE THREAD

**Issue by kikaragyozov** [soxtoby/SlackNet#219]
I have a `IBlockActionHandler`. It successfully gets invoked.

The problem occurs when I reach the final part of the method, mainly, the following:

```
 public async Task Handle(ButtonAction action, BlockActionRequest request)
{
  // ... Modify the original message where the buttonAction take place...

  // Finally, make the changes.
  await _slackApiClient.Respond(request, new MessageResponse()
  {
      Message = new()
      {
          Text = request.Message.Text,
          Blocks = newBlocks
      },
      ReplaceOriginal = true,
      DeleteOriginal = false,
      ResponseType = ResponseType.InChannel
  });
```

This throws with the following exception, when previously, it didn't throw anything:

```
16:37:17 ERR] Error handling request
  RequestId: 905c3504f8be436092836da201d8ee3a
  Source: SlackNet.SlackSocketModeClient
  Exception: System.Net.Http.HttpRequestException: The requested name is valid, but no data of the requested type was found. (hooks.slack.com:443)
 ---> System.Net.Sockets.SocketException (11004): The requested name is valid, but no data of the requested type was found.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionWithTelemetryAsync(HttpRequestMessage request, HttpConnectionPool pool, Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at SlackNet.Http.Execute[T](HttpRequestMessage requestMessage, Nullable`1 cancellationToken)
   at SlackNet.SlackApiClient.WebApiRequest[T](Func`1 createRequest, Nullable`1 cancellationToken)
   at Omitted) in Omitted
   at SlackNet.Handlers.SpecificBlockActionHandler.Handle(BlockActionRequest request, Responder respond)
   at SlackNet.SlackSocketModeClient.HandleBlockActions(SlackRequestContext requestContext, BlockActionRequest blockActions, Action`1 respond)
   at SlackNet.SlackSocketModeClient.HandleRequest(SocketEnvelope envelope)
   at SlackNet.SlackSocketModeClient.HandleRequest(SocketEnvelope envelope)
   ```

There's a previous exception in SlackNet.Http, about failing to send an HTTP Post mesage with the same reasoning.

**Comment by soxtoby** [comment]
Hi @kikaragyozov, this error looks like a DNS or related network issue. FWIW I've tested your code by replacing the `Chat.Update` call in [CounterDemo.cs](https://github.com/soxtoby/SlackNet/blob/bb77d4211b68e8a5e2b6f9dcc9e5c0a2a5012ca1/Examples/SlackNetDemo/CounterDemo.cs#L39) with `Respond`, and it seems to work fine.

**Comment by soxtoby** [comment]
The async interfaces and methods are marked as obsolete because they're experimental (see #44). Granted I raised that over 4 years ago now, but I still haven't figured out a good way to deal with Azure Functions shutting down after the response is sent, which basically breaks the current design 😩.
