### ISSUE TITLE
Concurrent reads or writes are not supported.

### ISSUE THREAD

**Issue by spairous** [soxtoby/SlackNet#43]
Hello All,

The below exception was thrown when using the events API and the example code you have provided.

The issue was visible when using the buttons provided while sending the "test interactivity" message on the bot.

Exception: 
System.InvalidOperationException: Concurrent reads or writes are not supported.
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult&amp; result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
   at SlackNet.AspNetCore.SlackRequestHandler.ReplaceRequestStreamWithMemoryStream(HttpRequest request) in C:\Sources\SlackNet\SlackNet.AspNetCore\SlackRequestHandler.cs:line 223
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at SlackNet.AspNetCore.SlackRequestHandler.ReadForm(HttpRequest request) in C:\Sources\SlackNet\SlackNet.AspNetCore\SlackRequestHandler.cs:line 263
   at SlackNet.AspNetCore.SlackRequestHandler.DeserializePayload[T](HttpRequest request) in C:\Sources\SlackNet\SlackNet.AspNetCore\SlackRequestHandler.cs:line 243
   at SlackNet.AspNetCore.SlackRequestHandler.HandleActionRequest(HttpRequest request, SlackEndpointConfiguration config) in C:\Sources\SlackNet\SlackNet.AspNetCore\SlackRequestHandler.cs:line 97
   at SlackNet.AspNetCore.SlackRequestMiddleware.Invoke(HttpContext context) in C:\Sources\SlackNet\SlackNet.AspNetCore\SlackRequestMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by spairous** [comment]
If you give me access i can upload the fix. (Patch attached...
[SlackNetIssue.txt](https://github.com/soxtoby/SlackNet/files/4610502/SlackNetIssue.txt)
)

**Comment by soxtoby** [comment]
Thanks for logging this. The fix will be included in the next release (hopefully within the next few days).
